name: sam2-env
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12.7
  - nvidia::cuda-toolkit=12.6.3
  - conda-forge::pytorch=2.5.1
  - conda-forge::torchvision=0.20.1
  - conda-forge::pandas=2.2.3
  - pip
  - pip:
    - matplotlib==3.10.1
    - opencv-python==4.11.0.86